# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oko < Formula
  desc "Browser CLI for coding agents, driving a dedicated Chrome over CDP"
  homepage "https://github.com/iamnikolie/oko"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iamnikolie/oko/releases/download/v0.4.0/oko_0.4.0_darwin_amd64.tar.gz"
      sha256 "9c34ef4cca0fa69650b07de7f97589e02f9cba2df6f3757a6fcb16d5516020cf"

      define_method(:install) do
        bin.install "oko"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iamnikolie/oko/releases/download/v0.4.0/oko_0.4.0_darwin_arm64.tar.gz"
      sha256 "bdbd4c728583aa53309a175b4e1679059cd3fc5b8c85044a508518c4346adafe"

      define_method(:install) do
        bin.install "oko"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamnikolie/oko/releases/download/v0.4.0/oko_0.4.0_linux_amd64.tar.gz"
      sha256 "af38fbfb2ed1629a428635f3884a0bae7c9e516dd114f96c5d66b84ec6a7c9a6"
      define_method(:install) do
        bin.install "oko"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamnikolie/oko/releases/download/v0.4.0/oko_0.4.0_linux_arm64.tar.gz"
      sha256 "023bd81116c66bc9c13e652592b360562842da2e9ec3aab3a81978c912ada43a"
      define_method(:install) do
        bin.install "oko"
      end
    end
  end

  test do
    assert_match(/^oko version /, shell_output("#{bin}/oko --version"))
  end
end
