# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oolog < Formula
  desc "OpenObserve logs from the terminal, built for coding agents"
  homepage "https://github.com/iamnikolie/oolog"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iamnikolie/oolog/releases/download/v0.1.1/oolog_0.1.1_darwin_amd64.tar.gz"
      sha256 "57f535d18355e6f9197aba9d271e4ab66d3a10979b3222605644ca7f00f09172"

      define_method(:install) do
        bin.install "oolog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iamnikolie/oolog/releases/download/v0.1.1/oolog_0.1.1_darwin_arm64.tar.gz"
      sha256 "887292569842487a65eebc6940719327126d678064c378bdb87e03ae196e9e25"

      define_method(:install) do
        bin.install "oolog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamnikolie/oolog/releases/download/v0.1.1/oolog_0.1.1_linux_amd64.tar.gz"
      sha256 "2e0dd47e6e6dbd9b08eaccbc0131abb1c4cb6bc9d11b48aeb7b651ed59828aa8"
      define_method(:install) do
        bin.install "oolog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamnikolie/oolog/releases/download/v0.1.1/oolog_0.1.1_linux_arm64.tar.gz"
      sha256 "c476b36b606f8239536f9403641ec36668e3bdcd87a2c969c42ca454a695021d"
      define_method(:install) do
        bin.install "oolog"
      end
    end
  end

  test do
    assert_match(/^oolog version /, shell_output("#{bin}/oolog version"))
  end
end
