# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackCli < Formula
  desc "Agent-facing Slack CLI with token-lean output"
  homepage "https://github.com/iamnikolie/slack-cli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iamnikolie/slack-cli/releases/download/v0.1.2/slack-cli_0.1.2_darwin_amd64.tar.gz"
      sha256 "ecf3f0020527641894286475f48fefd1bacf5b716a1e78a4b9fb9edf573a2dcb"

      define_method(:install) do
        bin.install "slk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iamnikolie/slack-cli/releases/download/v0.1.2/slack-cli_0.1.2_darwin_arm64.tar.gz"
      sha256 "cfefdc2687ba6b7272ddb80e6ca86cbf3ac4170429ba80a741e7c23c3ffe81ca"

      define_method(:install) do
        bin.install "slk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamnikolie/slack-cli/releases/download/v0.1.2/slack-cli_0.1.2_linux_amd64.tar.gz"
      sha256 "b3b64ef7002277622a3309d4ae4ae539584f263b6e8f4b4198a6846cf7986197"
      define_method(:install) do
        bin.install "slk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamnikolie/slack-cli/releases/download/v0.1.2/slack-cli_0.1.2_linux_arm64.tar.gz"
      sha256 "35c47235c80ea8e7a8798b8d7e0a621a403ae4bdb3e6ff50cfaa049b2e66221d"
      define_method(:install) do
        bin.install "slk"
      end
    end
  end

  test do
    assert_match(/^slk version /, shell_output("#{bin}/slk version"))
  end
end
